name: barcode_finder
description: Barcode Finder is a plugin for reading barcodes and QRCodes from pdf files and images using ML kit for Android and iOS
version: 0.0.6
homepage: https://github.com/PopcodeMobile/barcode-finder

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: br.com.popcode.barcode_finder
        pluginClass: BarcodeFinderPlugin
      ios:
        pluginClass: SwiftBarcodeFinderPlugin
