name: barcode_finder
description: Barcode Finder is a plugin for reading barcodes and QRCodes from pdf files and images using Zxing for Android and Zxing and Zbar for iOS
version: 0.1.0
homepage: https://github.com/PopcodeMobile/barcode-finder

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: "3.24.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: br.com.popcode.barcode_finder
        pluginClass: BarcodeFinderPlugin
      ios:
        pluginClass: SwiftBarcodeFinderPlugin
